image: alpine/edge
oauth: git.sr.ht/PROFILE:RO git.sr.ht/REPOSITORIES:RO git.sr.ht/OBJECTS:RW
secrets:
  - 178fd3d3-8d4e-4409-a8a6-3eb6a1a635bf
  - 5389faf3-af7e-47e5-a418-f9a002d3c4c2
sources:
  - git@git.sr.ht:~tpt/NoteworthyII
environment:
  versions: 10.2.5,3.4.3,1.15.0
  repo: NoteworthyII
packages:
  - openjdk17
  - hut
tasks:
  - get-release-version: |
      if [[ $GIT_REF != *"tag"* ]]; then \
        complete-build; \
      fi
      cd $repo
      echo "export NW_RELEASE_VERSION=${GIT_REF/refs\/tags\//}" >> ~/.buildenv
  - prepare-wrapper: |
      cd $repo
      chmod u+x ./nww.sh
  - get-changelog-delta: |
      cd $repo
      ./nww.sh changelog -vf $NW_RELEASE_VERSION > changelog.txt
  - package: |
      cd $repo
      ./nww.sh pack -pv $NW_RELEASE_VERSION
      echo "export NW_FILE=NoteworthyII_${NW_RELEASE_VERSION}.zip" >> ~/.buildenv
  - hash: |
      cd $repo
      ./nww.sh hash $NW_FILE > hash.md5
      ./nww.sh hash -a SHA-1 $NW_FILE > hash.sha1
  - upload-artifact: |
      cd $repo
      hut git artifact upload -r NoteworthyII --rev $NW_RELEASE_VERSION $NW_FILE
      hut git artifact upload -r NoteworthyII --rev $NW_RELEASE_VERSION hash.md5
      hut git artifact upload -r NoteworthyII --rev $NW_RELEASE_VERSION hash.sha1
  - curse-forge-release: |
      cd $repo
      export CF_API_TOKEN=$(cat ~/.cf-token)
      ./nww.sh upload -p NW_FILE -rv $NW_RELEASE_VERSION -gv $versions -v
