name: Publish a new release to GH and CF from tag

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "The supported WoW game version of this release."
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: prepare wrapper
        run: chmod u+x ./nww.sh
      - name: get release version
        run: echo "::set-output name=NW_RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}"
        id: nw-release-version
      - name: get changelog delta
        run: ./nww.sh changelog -vf $NWV >> delta.txt
        env:
          NWV: ${{ steps.nw-release-version.outputs.NW_RELEASE_VERSION }}
      - name: package
        run: ./nww.sh pack -pv $NWV
        env:
          NWV: ${{ steps.nw-release-version.outputs.NW_RELEASE_VERSION }}
      - name: view values
        run: echo version is ${{ steps.nw-release-version.outputs.NW_RELEASE_VERSION }}, changelog is ${cat delta.txt}
